---
- name: install containerd.conf
  copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf
  become: true

- name: Add the containerd requisite modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: 
    - overlay
    - br_netfilter
  become: true

- name: Set system configurations for Kubernetes networking
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  become: true

- ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
  become: True
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables
  
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: install containerd.conf
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
  become: true
  
- name: Install packages
  apt:
    pkg:
      - containerd
      - apt-transport-https
      - curl
      - kubelet=1.23.0-00
      - kubeadm=1.23.0-00
      - kubectl=1.23.0-00
    update_cache: yes
  become: true

- name: Hold kubeadm
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
   - kubelet
   - kubeadm
   - kubectl
  become: true

- name: Create default configuration file for containerd
  file:
    dest: /etc/containerd
    state: directory

- name: containerd default config
  copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml
  become: true

- name: restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Disable swap for current session
  command: swapoff -a
  become: true

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes


