---
- name: check instance status should be state ok
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: local
  gather_facts: false
  tasks:
  - name: check instance status should be state ok
    shell: |
      aws ec2 describe-instance-status --instance-ids {{ item }} --query "InstanceStatuses[*].InstanceStatus.Status" --output text
    register: result
    until: result.stdout == "ok"
    retries: 40
    delay: 15    # 15*40 = 600 ~= 10 mins
    loop: "{{ inst_list }}"
    
- name: Configure instance(s)
  hosts: k8s_control
  vars_files:
      - vars/vars_sandbox_aws.yml
  become: True
  gather_facts: True
  roles:
    - k8s_control

- name: Configure instance(s)
  hosts: k8s_node
  vars_files:
      - vars/vars_sandbox_aws.yml
  become: True
  gather_facts: True
  roles:
    - k8s_node