---
- name: Create k8s_control
  hosts: localhost 
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: local
    role: k8s_control
  vars_files:
      - vars/vars_sandbox_aws.yml
  gather_facts: False
  tasks:
    - name: Launch {{ role }} instance(s)
      amazon.aws.ec2_instance:
        name: "{{ role }}_{{ item }}_{{ lookup('env', 'USER') }}"
        key_name: k8s_key
        vpc_subnet_id: "{{ k8s_subnet.subnet.id }}"
        instance_type: "{{ k8s_control_instance_type }}"
        security_group: "{{ k8s_sg.group_id }}"
        #user_data: "{{ lookup('file', 'ubuntu_user_data') }}"  ### use this to take action on your ec2 instance before connecting with ssh or ansible
        #instace_role: "{{ role }}"  #### use this to assign a previously created iam role to your ec2 instance
        network:
          assign_public_ip: true
        image_id: "{{ latestAMI.image_id }}"
        tags:
          k8s_role: "{{ role }}"
          owner: "{{ lookup('env', 'USER') }}" 
        state: running
        wait: true
      loop:
        - 01
      