---
- name: Restart instances
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: local
  gather_facts: false
  tasks:
    - name: Restart instances
      community.aws.ec2_instance:
        state: restarted
        filters:
          "tag:k8s_role":
            - "{{ role }}"
          "tag:owner":
            - "{{ lookup('env', 'USER') }}"
      register: instances
      async: 60
      poll: 5
      
    - name: print instances
      debug:
        msg: "{{ instances }}"
